identv nova-network.log 2015-07-07 21:21:21.194 19105 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
identv nova-network.log 2015-07-07 21:21:21.228 19105 ERROR oslo_messaging._drivers.common [req-96681641-9c85-486b-af93-d7a94419fbb5 ] ['Traceback (most recent call last):\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply\n    executor_callback))\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch\n    executor_callback)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch\n    result = func(ctxt, **new_args)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1763, in update_network\n    self._populate_v4_net(new_net, new_v4_subnet, **kwargs)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1705, in _populate_v4_net\n    net[\'range_end\'] = self._calculate_range_end(subnet_v4, kwargs)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1734, in _calculate_range_end\n    raise exception.FixedIpRangeEndInvalid(address=range_end)\n', 'FixedIpRangeEndInvalid: End of IP subrange 10.21.2.254 is invalid.\n']
identv nova-network.log 2015-07-07 21:21:45.360 19105 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
identv nova-network.log 2015-07-07 21:21:45.364 19105 ERROR oslo_messaging._drivers.common [req-38e9237d-faca-4926-984d-a1dfcb4a221e ] ['Traceback (most recent call last):\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply\n    executor_callback))\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch\n    executor_callback)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch\n    result = func(ctxt, **new_args)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1763, in update_network\n    self._populate_v4_net(new_net, new_v4_subnet, **kwargs)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1705, in _populate_v4_net\n    net[\'range_end\'] = self._calculate_range_end(subnet_v4, kwargs)\n', '  File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1734, in _calculate_range_end\n    raise exception.FixedIpRangeEndInvalid(address=range_end)\n', 'FixedIpRangeEndInvalid: End of IP subrange 10.21.2.254 is invalid.\n']
